namespace :cook do
  task :default do
    rsync
    apply
    cleanup
  end

  task :rsync do
    find_servers.each do |server|
      port = Pupcap::Command.server_port(self, server)
      host = Pupcap::Command.server_host(self, server)
      ssh_cmd = "-e \"ssh -p #{port} -i #{provision_key}\""
      rsync_options = "-p --chmod=o+r,g+r -az"
      cmd = "rsync #{rsync_options} #{ssh_cmd} #{local_root}/puppet/ #{host}:#{deploy_to}"
      logger.important(cmd)
      system(cmd)
    end
  end

  task :apply do
    modules = "--modulepath=#{deploy_to}/modules:#{deploy_to}/manifests"
    nook = pupcap_options[:noop] ? "--noop" : ""
    debug = pupcap_options[:debug] ? "--debug" : ""
    sudo("/usr/local/bin/puppet apply --detailed-exitcodes #{nook} #{debug} #{modules} #{deploy_to}/manifests/#{ENV["ROLES"]}.pp || true")
  end

  task :cleanup do
    run("rm -rf #{deploy_to}")
  end
end
