require 'erb'

namespace :cook do
  task :default do
    rsync
    apply
    cleanup
  end

  task :rsync do
    find_servers.each do |server|
      port = Pupcap::Command.server_port(self, server)
      host = Pupcap::Command.server_host(self, server)
      ssh_cmd = "-e \"ssh -p #{port} -i #{provision_key}\""
      rsync_options = "-p --chmod=o+r,g+r -az"
      cmd = "rsync #{rsync_options} #{ssh_cmd} #{local_root}/puppet/ #{host}:#{deploy_to}"
      logger.important(cmd)
      system(cmd)
    end
  end

  task :apply do
    remote_command = "#{deploy_to}/apply.sh"

    puppet = "/usr/local/bin/puppet"
    modules = "--modulepath=#{deploy_to}/modules:#{deploy_to}/manifests"
    nook = pupcap_options[:noop] ? " --noop" : ""
    debug = pupcap_options[:debug] ? " --debug --verbose" : ""

    erb = ERB.new(File.read("#{pupcap_root}/action/cook/apply.sh.erb"))
    rs = erb.result(binding)

    put(rs, remote_command)
    run("chmod +x #{remote_command}")
    sudo("#{remote_command} \"$CAPISTRANO:HOSTROLES$\"")
  end

  task :cleanup do
    run("rm -rf #{deploy_to}")
  end
end
